spring.application.name=gateway-service

# Simple route to forward API requests to the data-service
spring.cloud.gateway.routes[0].id=data-service
spring.cloud.gateway.routes[0].uri=http://data-service-1:8080
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/**
